### ISSUE TITLE
accessing functions that are inside floc_model

### ISSUE THREAD

**Issue by monroews** [AguaClara/aguaclara_research#11]
What does from aguaclara_research.play import * load? It doesn't appear that this loads any of the modules that are inside aguaclara_research.
How do I access functions inside floc_model, for example?

**Comment by fletchapin** [comment]
I can change it so that ```aguaclara_research.play import *``` loads the modules such as floc_model.py (thinking about it now I think that's a good idea, so I'll work on getting that started for the next pip release). At the moment it is just loading dependencies such as scipy and aide_design.

For now you could use ```from aguaclara_research import floc_model```

**Comment by fletchapin** [comment]
@monroews I updated ```aguaclara_research.play``` so that on the next release it will have floc_model and the other modules imported.
