### ISSUE TITLE
G coil equation is wrong in floc_model

### ISSUE THREAD

**Issue by monroews** [AguaClara/aguaclara_research#20]
The Gcoil equation has the wrong term raised to the 4th power
Also verify that the correct log base 10 is used.

$$\overline{G_{coil}} = \bar G\left[ 1 + 0.033\left(log_{10}De\right)^4  \right]^\frac{1}{2} $$

**Comment by fletchapin** [comment]
I just checked floc_model and the log base 10 term is raised to the 4th power as shown in the LaTeX equation above.
