### ISSUE TITLE
Tutorial and Research Organization

### ISSUE THREAD

**Issue by IanCullings** [AguaClara/aguaclara_research#25]
After discussing this, Hannah and I had an idea for a new structure for organizing tutorials, report templates, and assignments. @monroews  @ethan92429 what are your thoughts?  Naming structure is also not final, and suggestions are welcome there as well.

* aguaclara_orientation repository: general tutorials applicable to all team members, including assignments like the python tutorial, tutorials on Github, and research report templates.  Strong tutorials written and reviewed by team leadership.   

* aguaclara_tutorial: slightly more specific tutorials that team members believe would be helpful for their subteam as well as other subteams. Tutorials in this repo would be written by all team members and be available as a resource, but not required learning for everyone. This repository will need to be well organized by larger categories such as research topics, Fabrication, and Going Global.

* subteam tutorials: tutorials specific to a subteam, written in the wiki section of the subteam's own Github repository.

* aguaclara_research: Wiki would contain information on functions as well as example markdown documents used for running calculations as you would in your report.

**Comment by monroews** [comment]
I'd suggest that aguaclara_orientation, aguaclara_tutorial, and the tutorials associated with aguaclara_research be combined into a single repo. The distinctions aresmall and would make it more difficult for students to find the tutorial of interest.

**Comment by eak24** [comment]
I agree that the distinctions are too small to warrant another repo. But we can always organize within the AguaClara repo with folders.

**Comment by IanCullings** [comment]
Makes sense.  I've opened another issue in aguaclara_tutorial to complete this organization before the next semester starts.  We'll be talking with the team leads as well about the process for writing and reviewing further tutorials.
