### ISSUE TITLE
General Recommendations for ProCoDA_Parser.py

### ISSUE THREAD

**Issue by WPennock** [AguaClara/aguaclara_research#7]
Based on my quick glance at the last two functions in ProCoDA_Parser.py, here are a few features I think might be good to add:
- In the annotations for the function, it would be good to include with every path variable that the directories should be divided by `\\` rather than `\`.
- It would be helpful if the functions also took as an input a list of the MetaIDs you wanted. Not all experiments may be valid or comparable to one another, so it would be good to be able to input a list of only the experiments you want to analyze in the particular way you are describing with the function.
- I don't know how much overhead it would add (maybe a lot), but it would be nice if rather than restricting it to column indices, users could also use strings from the headers in their data files that the function would then search for and match to to find the proper index (e.g., ["Influent Turbidity (NTU)"]). The reason this is a useful feature is that the indices of data files can be shifted by adding or removing a sensor or function. So, if a team decides they want to add a pH probe to their apparatus, their previous data processor will have to be done in two steps: one for the old format of data files, and one for the new format.
- I do not believe the current way the functions load the metafile that it will be able to read .xls files. Can the function be generalized to do that? Since it will be most convenient for teams to use Excel instead of tab-delimited .txt files, this would streamline things a bit. Otherwise, we'll need to let them know that they'll need to save a version of their .xls files as a tab-delimited .txt. This could become an issue if they save updates to their .xls file but forget to save them to their .txt file.

Great work, Fletcher! I'm very excited by the promise of this module!

**Comment by fletchapin** [comment]
@WPennock Good suggestions! I'll start to work on them soon. I'll create a new branch as well, since we should start to work using version branches and then merging into master rather than editing master directly

**Comment by fletchapin** [comment]
Also @WPennock the input for individual ProCoDA files is the original ```.xls``` file, and those are tab delimited. 

I'm not sure how to ensure that ```.xls``` files are tab delimited, but that's necessary for the ```read_csv``` function to work properly.

**Comment by fletchapin** [comment]
@WPennock these have been addressed in the new branch I made, procoda_parser, and it'd be great if you could test them out
